os:
    - linux
language: node_js
node_js:
    - "8.9.1"
before_install:
    - npm install -g npm
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    - yarn install
    - yarn link
script:
    - yarn test
